package com.drizzly.springmvc.model;
// Generated 17 Oct, 2015 9:14:35 PM by Hibernate Tools 4.3.1


import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DrMaEmployee generated by hbm2java
 */
@Entity
@Table(name = "DR_MA_EMPLOYEE")
public class DrMaEmployee  implements java.io.Serializable,IEmployee {

    @Id
    @Column(name = "EM_ID")
    @GeneratedValue
     private Long emId;
    @Column(name = "EM_NAME")
     private String emName;
    @Column(name = "EM_JOIN_DATE")
     private Date emJoinDate;
    @Column(name = "EM_SALARY")
    private BigInteger emSalary=new BigInteger("0");
    @Column(name = "EM_RELEIVED_DATE")
     private Date emReleivedDate;
    @Column(name = "EM_ADDRESS")
     private String emAddress;
    @Column(name = "EM_CITY")
    private String emCity="chennai";
    @Column(name = "EM_STATE")
    private String emState="TamilNadu";
    @Column(name = "EM_PINCODE")
     private String emPincode;
    @Column(name = "EM_COUNTRY")
    private String emCountry="India";
    @Column(name = "EM_MOBILE1")
     private String emMobile1;
    @Column(name = "EM_MOBILE2")
     private String emMobile2;
    @Column(name = "EM_EMAIL1")
     private String emEmail1;

//    @OneToMany
//    @JoinColumn(name = "LP_EM_ID")
//    private Set drTrLoanDues = new HashSet(0);
//    @OneToMany
//    @JoinColumn(name = "LN_EM_ID")
//    private Set drTrLoans = new HashSet(0);

    public DrMaEmployee() {
    }

	
    public DrMaEmployee(String emName, Date emJoinDate, BigInteger emSalary, String emAddress, String emCity, String emState, String emPincode, String emCountry, String emMobile1) {
        this.emName = emName;
        this.emJoinDate = emJoinDate;
        this.emSalary = emSalary;
        this.emAddress = emAddress;
        this.emCity = emCity;
        this.emState = emState;
        this.emPincode = emPincode;
        this.emCountry = emCountry;
        this.emMobile1 = emMobile1;
    }
    public DrMaEmployee(String emName, Date emJoinDate, BigInteger emSalary, Date emReleivedDate, String emAddress, String emCity, String emState, String emPincode, String emCountry, String emMobile1, String emMobile2, String emEmail1, Set drTrLoanDues, Set drTrLoans) {
       this.emName = emName;
       this.emJoinDate = emJoinDate;
       this.emSalary = emSalary;
       this.emReleivedDate = emReleivedDate;
       this.emAddress = emAddress;
       this.emCity = emCity;
       this.emState = emState;
       this.emPincode = emPincode;
       this.emCountry = emCountry;
       this.emMobile1 = emMobile1;
       this.emMobile2 = emMobile2;
       this.emEmail1 = emEmail1;
//       this.drTrLoanDues = drTrLoanDues;
//       this.drTrLoans = drTrLoans;
//       this.drTrEnquriys = drTrEnquriys;
    }
   
    public Long getEmId() {
        return this.emId;
    }
    
    public void setEmId(Long emId) {
        this.emId = emId;
    }
    @Override
    public String getEmName() {
        return this.emName;
    }
    
    public void setEmName(String emName) {
        this.emName = emName;
    }
    @Override
    public Date getEmJoinDate() {
        return this.emJoinDate;
    }
    
    public void setEmJoinDate(Date emJoinDate) {
        this.emJoinDate = emJoinDate;
    }
    public BigInteger getEmSalary() {
        return this.emSalary;
    }
    
    public void setEmSalary(BigInteger emSalary) {
        this.emSalary = emSalary;
    }
    public Date getEmReleivedDate() {
        return this.emReleivedDate;
    }
    
    public void setEmReleivedDate(Date emReleivedDate) {
        this.emReleivedDate = emReleivedDate;
    }
    @Override
    public String getEmAddress() {
        return this.emAddress;
    }
    
    public void setEmAddress(String emAddress) {
        this.emAddress = emAddress;
    }
    @Override
    public String getEmCity() {
        return this.emCity;
    }
    
    public void setEmCity(String emCity) {
        this.emCity = emCity;
    }
    @Override
    public String getEmState() {
        return this.emState;
    }
    
    public void setEmState(String emState) {
        this.emState = emState;
    }
    @Override
    public String getEmPincode() {
        return this.emPincode;
    }
    
    public void setEmPincode(String emPincode) {
        this.emPincode = emPincode;
    }
    @Override
    public String getEmCountry() {
        return this.emCountry;
    }
    
    public void setEmCountry(String emCountry) {
        this.emCountry = emCountry;
    }
    @Override
    public String getEmMobile1() {
        return this.emMobile1;
    }
    
    public void setEmMobile1(String emMobile1) {
        this.emMobile1 = emMobile1;
    }
    @Override
    public String getEmMobile2() {
        return this.emMobile2;
    }
    
    public void setEmMobile2(String emMobile2) {
        this.emMobile2 = emMobile2;
    }
    @Override
    public String getEmEmail1() {
        return this.emEmail1;
    }
    
    public void setEmEmail1(String emEmail1) {
        this.emEmail1 = emEmail1;
    }
//    @Override
//    public Set getDrTrLoanDues() {
//        return this.drTrLoanDues;
//    }
//    
//    public void setDrTrLoanDues(Set drTrLoanDues) {
//        this.drTrLoanDues = drTrLoanDues;
//    }
//    @Override
//    public Set getDrTrLoans() {
//        return this.drTrLoans;
//    }
//    
//    public void setDrTrLoans(Set drTrLoans) {
//        this.drTrLoans = drTrLoans;
//    }

    @Override
    public String toString() {
        return "DrMaEmployee{" + "emId=" + emId + ", emName=" + emName + ", emJoinDate=" + emJoinDate + ", emSalary=" + emSalary + ", emReleivedDate=" + emReleivedDate + ", emAddress=" + emAddress + ", emCity=" + emCity + ", emState=" + emState + ", emPincode=" + emPincode + ", emCountry=" + emCountry + ", emMobile1=" + emMobile1 + ", emMobile2=" + emMobile2 + ", emEmail1=" + emEmail1 + '}';
    }
    

    
    }

    
