package com.drizzly.springmvc.model;
// Generated 8 Aug, 2016 8:57:08 AM by Hibernate Tools 4.3.1


import com.drizzly.springmvc.configuration.*;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DrTrEnquriy generated by hbm2java
 */
@Entity
@Table(name="DR_TR_ENQURIY"
    ,catalog="DrizzlyDB"
)
public class DrTrEnquriy  implements java.io.Serializable {


     private long eqId;
     private DrMaEmployee drMaEmployee;
     private String eqStudentName;
     private String eqFatherName;
     private String eqCategory;
     private String eqMobileNumber;
     private String eqNote;

    public DrTrEnquriy() {
    }

	
    public DrTrEnquriy(long eqId, DrMaEmployee drMaEmployee, String eqStudentName, String eqCategory, String eqMobileNumber) {
        this.eqId = eqId;
        this.drMaEmployee = drMaEmployee;
        this.eqStudentName = eqStudentName;
        this.eqCategory = eqCategory;
        this.eqMobileNumber = eqMobileNumber;
    }
    public DrTrEnquriy(long eqId, DrMaEmployee drMaEmployee, String eqStudentName, String eqFatherName, String eqCategory, String eqMobileNumber, String eqNote) {
       this.eqId = eqId;
       this.drMaEmployee = drMaEmployee;
       this.eqStudentName = eqStudentName;
       this.eqFatherName = eqFatherName;
       this.eqCategory = eqCategory;
       this.eqMobileNumber = eqMobileNumber;
       this.eqNote = eqNote;
    }
   
     @Id 

    
    @Column(name="EQ_ID", unique=true, nullable=false)
    public long getEqId() {
        return this.eqId;
    }
    
    public void setEqId(long eqId) {
        this.eqId = eqId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EQ_STAFF", nullable=false)
    public DrMaEmployee getDrMaEmployee() {
        return this.drMaEmployee;
    }
    
    public void setDrMaEmployee(DrMaEmployee drMaEmployee) {
        this.drMaEmployee = drMaEmployee;
    }

    
    @Column(name="EQ_STUDENT_NAME", nullable=false, length=100)
    public String getEqStudentName() {
        return this.eqStudentName;
    }
    
    public void setEqStudentName(String eqStudentName) {
        this.eqStudentName = eqStudentName;
    }

    
    @Column(name="EQ_FATHER_NAME", length=100)
    public String getEqFatherName() {
        return this.eqFatherName;
    }
    
    public void setEqFatherName(String eqFatherName) {
        this.eqFatherName = eqFatherName;
    }

    
    @Column(name="EQ_CATEGORY", nullable=false, length=100)
    public String getEqCategory() {
        return this.eqCategory;
    }
    
    public void setEqCategory(String eqCategory) {
        this.eqCategory = eqCategory;
    }

    
    @Column(name="EQ_MOBILE_NUMBER", nullable=false, length=45)
    public String getEqMobileNumber() {
        return this.eqMobileNumber;
    }
    
    public void setEqMobileNumber(String eqMobileNumber) {
        this.eqMobileNumber = eqMobileNumber;
    }

    
    @Column(name="EQ_NOTE", length=100)
    public String getEqNote() {
        return this.eqNote;
    }
    
    public void setEqNote(String eqNote) {
        this.eqNote = eqNote;
    }




}


