package com.drizzly.springmvc.model;
// Generated 17 Oct, 2015 9:14:35 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.math.BigInteger;
import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DrTrFeesDue generated by hbm2java
 */
@Entity
@Table(name = "DR_TR_FEES_DUE")
public class DrTrFeesDue  implements java.io.Serializable, IFeesDue {

    @Id
    @GeneratedValue
    @Column(name = "FP_ID")
    private Long fpId;
    @Column(name = "FP_PAID_AMOUNT")
    private BigInteger fpPaidAmount;
    @Column(name = "FP_PAID_DATE")
    private Date fpPaidDate;
    @Column(name = "FP_PAID_MODE")
    private String fpPaidMode;
    @Column(name = "FP_PAID_NOTE")
    private String fpNote;
    @Column(name = "FP_PAID_TO_STAFF")
    private Long fpPaidToStaff;
//    @ManyToOne(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
//    @JoinColumn(name="FP_ST_ID")
//    @JsonBackReference
//    private DrMaStudent drMaStudent;
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FP_ST_ID")
    @JsonBackReference
    private DrMaStudent drMaStudent;

    public DrTrFeesDue() {
    }

	
    public DrTrFeesDue(DrMaStudent drMaStudent, BigInteger fpAmountPaid, Date fpPaidDate) {
        this.drMaStudent = drMaStudent;
        this.fpPaidAmount = fpAmountPaid;
        this.fpPaidDate = fpPaidDate;
    }
    public DrTrFeesDue(DrMaStudent drMaStudent, BigInteger fpAmountPaid, Date fpPaidDate, String fpPaidMode) {
       this.drMaStudent = drMaStudent;
       this.fpPaidAmount = fpAmountPaid;
       this.fpPaidDate = fpPaidDate;
       this.fpPaidMode = fpPaidMode;
    }
    @Override
    public Long getFpPaidToStaff() {
        return fpPaidToStaff;
    }

    public void setFpPaidToStaff(Long fpPaidToStaff) {
        this.fpPaidToStaff = fpPaidToStaff;
    }
    
    @Override
    public Long getFpId() {
        return this.fpId;
    }
    
    public void setFpId(Long fpId) {
        this.fpId = fpId;
    }
    @Override
    public DrMaStudent getDrMaStudent() {
        return this.drMaStudent;
    }
    
    public void setDrMaStudent(DrMaStudent drMaStudent) {
        this.drMaStudent = drMaStudent;
    }
    @Override
    public BigInteger getFpPaidAmount() {
        return this.fpPaidAmount;
    }
    
    public void setFpPaidAmount(BigInteger fpPaidAmount) {
        this.fpPaidAmount = fpPaidAmount;
    }
    @Override
    public Date getFpPaidDate() {
        return this.fpPaidDate;
    }
    
    public void setFpPaidDate(Date fpPaidDate) {
        this.fpPaidDate = fpPaidDate;
    }
    @Override
    public String getFpPaidMode() {
        return this.fpPaidMode;
    }
    
    public void setFpMode(String fpPaidMode) {
        this.fpPaidMode = fpPaidMode;
    }

    public String getFpNote() {
        return fpNote;
    }

    public void setFpNote(String fpNote) {
        this.fpNote = fpNote;
    }

    @Override
    public String toString() {
        return "DrTrFeesDue{" + "fpId=" + fpId + ", fpPaidAmount=" + fpPaidAmount + ", fpPaidDate=" + fpPaidDate + ",   fpPaidToStaff="+fpPaidToStaff+'}';
    }

    
}


